/**
 * PILOT+ — Corporate Brief PDF
 * 1-page executive document generated by AI.
 * Target reader: sales director, 30-second read.
 */

import React from 'react'
import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'

// ── Palette ───────────────────────────────────────────────────────────────────
const C = {
  navy:      '#0a1628',
  navyMid:   '#112240',
  blue:      '#1d4ed8',
  blueLight: '#3b82f6',
  accent:    '#60a5fa',
  green:     '#16a34a',
  greenPale: '#dcfce7',
  red:       '#dc2626',
  redPale:   '#fee2e2',
  amber:     '#d97706',
  amberPale: '#fef9c3',
  white:     '#ffffff',
  offWhite:  '#f8fafc',
  gray100:   '#f1f5f9',
  gray200:   '#e2e8f0',
  gray400:   '#94a3b8',
  gray600:   '#475569',
  gray800:   '#1e293b',
  gold:      '#f59e0b',
  goldPale:  '#fef3c7',
}

// ── Styles ────────────────────────────────────────────────────────────────────
const s = StyleSheet.create({
  page: {
    backgroundColor: C.white,
    fontFamily: 'Helvetica',
    fontSize: 8.5,
    color: C.gray800,
    paddingBottom: 0,
  },

  // ─ Top bar
  topBar: {
    backgroundColor: C.navy,
    paddingHorizontal: 28,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topBarLogo: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: C.white, letterSpacing: 1 },
  topBarLogoPlus: { color: C.accent },
  topBarLabel: { fontSize: 8, color: C.accent, letterSpacing: 2, fontFamily: 'Helvetica-Bold' },
  topBarDate: { fontSize: 7.5, color: C.gray400 },

  // ─ Hero
  hero: {
    backgroundColor: C.navyMid,
    paddingHorizontal: 28,
    paddingTop: 16,
    paddingBottom: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  heroLeft: { flex: 1, marginRight: 20 },
  heroTitle: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: C.white, marginBottom: 4, lineHeight: 1.2 },
  heroSub: { fontSize: 9, color: C.gray400, marginBottom: 2 },
  heroBadge: {
    backgroundColor: 'rgba(96,165,250,0.15)',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
    marginTop: 6,
  },
  heroBadgeText: { fontSize: 7, color: C.accent, fontFamily: 'Helvetica-Bold', letterSpacing: 0.5 },

  // ─ Body
  body: {
    paddingHorizontal: 28,
    paddingTop: 18,
    paddingBottom: 14,
    flexDirection: 'row',
    gap: 16,
  },

  // ─ Left column — verdict + score
  colLeft: { width: 130 },

  verdictBox: {
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginBottom: 10,
  },
  verdictLabel: { fontSize: 7, fontFamily: 'Helvetica-Bold', letterSpacing: 2, marginBottom: 6 },
  verdictText: { fontSize: 26, fontFamily: 'Helvetica-Bold', letterSpacing: 1 },

  scoreCard: {
    backgroundColor: C.gray100,
    borderRadius: 6,
    padding: 10,
    marginBottom: 8,
  },
  scoreLabel: { fontSize: 7, color: C.gray600, marginBottom: 4 },
  scoreValue: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: C.navy, marginBottom: 6 },
  scoreBarBg: { backgroundColor: C.gray200, borderRadius: 3, height: 5 },
  scoreBarFill: { borderRadius: 3, height: 5 },

  metaItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 5 },
  metaDot: { width: 5, height: 5, borderRadius: 3, marginRight: 6 },
  metaLabel: { fontSize: 6.5, color: C.gray600, marginRight: 4 },
  metaValue: { fontSize: 7, fontFamily: 'Helvetica-Bold', color: C.gray800 },

  // ─ Right column — key points + financials
  colRight: { flex: 1 },

  sectionTitle: {
    fontSize: 6.5,
    fontFamily: 'Helvetica-Bold',
    color: C.gray400,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 4,
  },

  pointRow: { flexDirection: 'row', marginBottom: 6, alignItems: 'flex-start' },
  pointIndex: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: C.blue,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    flexShrink: 0,
  },
  pointIndexText: { fontSize: 7, fontFamily: 'Helvetica-Bold', color: C.white },
  pointText: { flex: 1, fontSize: 8.5, color: C.gray800, lineHeight: 1.45 },

  divider: { height: 1, backgroundColor: C.gray200, marginVertical: 10 },

  finRow: { flexDirection: 'row', gap: 8, marginBottom: 0 },
  finCard: { flex: 1, borderRadius: 6, padding: 9 },
  finLabel: { fontSize: 6.5, color: C.gray600, marginBottom: 3, letterSpacing: 0.5 },
  finValue: { fontSize: 10, fontFamily: 'Helvetica-Bold' },
  finSub: { fontSize: 7, color: C.gray600, marginTop: 2 },

  // ─ Recommendation bar
  recoBar: {
    marginHorizontal: 28,
    backgroundColor: C.goldPale,
    borderRadius: 6,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderLeftWidth: 3,
    borderLeftColor: C.gold,
    marginBottom: 16,
  },
  recoIcon: { fontSize: 10, marginRight: 8, marginTop: 1 },
  recoContent: { flex: 1 },
  recoTitle: { fontSize: 7, fontFamily: 'Helvetica-Bold', color: C.amber, letterSpacing: 1, marginBottom: 4 },
  recoText: { fontSize: 8.5, color: C.gray800, lineHeight: 1.5 },

  // ─ Risk strip
  riskStrip: {
    marginHorizontal: 28,
    backgroundColor: C.redPale,
    borderRadius: 5,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    borderLeftWidth: 3,
    borderLeftColor: C.red,
  },
  riskLabel: { fontSize: 6.5, fontFamily: 'Helvetica-Bold', color: C.red, marginRight: 8, letterSpacing: 1 },
  riskText: { fontSize: 8, color: C.gray800, flex: 1 },

  // ─ Footer
  footer: {
    backgroundColor: C.navy,
    paddingHorizontal: 28,
    paddingVertical: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
  },
  footerLeft: { fontSize: 7, color: C.gray400 },
  footerCenter: { fontSize: 6.5, color: C.gray400, letterSpacing: 1 },
  footerRight: { fontSize: 7, color: C.accent },
})

// ── Types ─────────────────────────────────────────────────────────────────────
export interface CorporatePDFProps {
  project: {
    name: string
    client: string
    location?: string
    offer_deadline?: string
    consultation_type?: string
  }
  score: { total_score: number; verdict: 'GO' | 'NO_GO' | 'A_ETUDIER' } | null
  keyPoints: string[]          // max 3
  mainRisk: string | null
  budget: string | null
  recommendation: string       // AI-generated 1-sentence
  generatedAt: string
  userCompany?: string
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function verdictConfig(v: string) {
  if (v === 'GO')       return { bg: C.greenPale, color: C.green,  label: 'GO', sublabel: 'Dossier recommandé' }
  if (v === 'NO_GO')    return { bg: C.redPale,   color: C.red,    label: 'NO GO', sublabel: 'Dossier déconseillé' }
  return                       { bg: C.amberPale, color: C.amber,  label: 'À ÉTUDIER', sublabel: 'Analyse approfondie requise' }
}

function scoreColor(s: number) {
  if (s >= 75) return C.green
  if (s >= 50) return C.amber
  return C.red
}

function fmtDate(iso?: string) {
  if (!iso) return 'N/D'
  return new Date(iso).toLocaleDateString('fr-FR', { day: '2-digit', month: 'short', year: 'numeric' })
}

// ── Component ─────────────────────────────────────────────────────────────────
export function CorporatePDF({
  project, score, keyPoints, mainRisk, budget, recommendation, generatedAt, userCompany,
}: CorporatePDFProps) {
  const vc   = verdictConfig(score?.verdict ?? 'A_ETUDIER')
  const pts  = keyPoints.slice(0, 3)
  const sc   = score?.total_score ?? 0
  const scColor = scoreColor(sc)

  return (
    <Document>
      <Page size="A4" style={s.page}>

        {/* ── Top bar */}
        <View style={s.topBar}>
          <View>
            <Text style={s.topBarLogo}>
              PILOT<Text style={s.topBarLogoPlus}>+</Text>
            </Text>
          </View>
          <Text style={s.topBarLabel}>BRIEF COMMERCIAL</Text>
          <Text style={s.topBarDate}>Généré le {fmtDate(generatedAt)}</Text>
        </View>

        {/* ── Hero */}
        <View style={s.hero}>
          <View style={s.heroLeft}>
            <Text style={s.heroTitle}>{project.name}</Text>
            <Text style={s.heroSub}>{project.client}</Text>
            {project.location && <Text style={s.heroSub}>{project.location}</Text>}
            {project.consultation_type && (
              <View style={s.heroBadge}>
                <Text style={s.heroBadgeText}>{project.consultation_type.toUpperCase()}</Text>
              </View>
            )}
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            {project.offer_deadline && (
              <View>
                <Text style={{ fontSize: 7, color: C.gray400, marginBottom: 2 }}>ÉCHÉANCE</Text>
                <Text style={{ fontSize: 11, fontFamily: 'Helvetica-Bold', color: C.white }}>
                  {fmtDate(project.offer_deadline)}
                </Text>
              </View>
            )}
            {userCompany && (
              <Text style={{ fontSize: 7, color: C.gray400, marginTop: 8 }}>{userCompany}</Text>
            )}
          </View>
        </View>

        {/* ── Body */}
        <View style={s.body}>

          {/* Left col */}
          <View style={s.colLeft}>

            {/* Verdict */}
            <View style={[s.verdictBox, { backgroundColor: vc.bg }]}>
              <Text style={[s.verdictLabel, { color: vc.color }]}>VERDICT</Text>
              <Text style={[s.verdictText, { color: vc.color }]}>{vc.label}</Text>
              <Text style={{ fontSize: 6.5, color: vc.color, marginTop: 5, textAlign: 'center' }}>
                {vc.sublabel}
              </Text>
            </View>

            {/* Score */}
            {score && (
              <View style={s.scoreCard}>
                <Text style={s.scoreLabel}>SCORE GLOBAL</Text>
                <Text style={[s.scoreValue, { color: scColor }]}>{sc}<Text style={{ fontSize: 11, color: C.gray400 }}>/100</Text></Text>
                <View style={s.scoreBarBg}>
                  <View style={[s.scoreBarFill, { width: `${sc}%`, backgroundColor: scColor }]} />
                </View>
              </View>
            )}

            {/* Meta */}
            <View style={s.metaItem}>
              <View style={[s.metaDot, { backgroundColor: C.blue }]} />
              <Text style={s.metaLabel}>Type</Text>
              <Text style={s.metaValue}>{project.consultation_type ?? 'Appel d\'offres'}</Text>
            </View>
            {budget && (
              <View style={s.metaItem}>
                <View style={[s.metaDot, { backgroundColor: C.green }]} />
                <Text style={s.metaLabel}>Budget</Text>
                <Text style={s.metaValue}>{budget}</Text>
              </View>
            )}
          </View>

          {/* Right col */}
          <View style={s.colRight}>
            <Text style={s.sectionTitle}>Points clés</Text>

            {pts.length > 0
              ? pts.map((pt, i) => (
                <View key={i} style={s.pointRow}>
                  <View style={s.pointIndex}>
                    <Text style={s.pointIndexText}>{i + 1}</Text>
                  </View>
                  <Text style={s.pointText}>{pt}</Text>
                </View>
              ))
              : (
                <Text style={{ fontSize: 8, color: C.gray400 }}>Aucun point clé disponible.</Text>
              )
            }

            <View style={s.divider} />

            {/* Financials row */}
            <Text style={s.sectionTitle}>Financier</Text>
            <View style={s.finRow}>
              <View style={[s.finCard, { backgroundColor: C.gray100 }]}>
                <Text style={s.finLabel}>MONTANT ESTIMÉ</Text>
                <Text style={[s.finValue, { color: C.navy }]}>{budget ?? 'N/C'}</Text>
                <Text style={s.finSub}>selon documents</Text>
              </View>
              <View style={[s.finCard, { backgroundColor: score && sc >= 75 ? C.greenPale : score && sc >= 50 ? C.amberPale : C.redPale }]}>
                <Text style={s.finLabel}>RENTABILITÉ</Text>
                <Text style={[s.finValue, { color: score && sc >= 75 ? C.green : score && sc >= 50 ? C.amber : C.red }]}>
                  {!score ? 'N/A' : sc >= 75 ? 'Élevée' : sc >= 50 ? 'Moyenne' : 'Faible'}
                </Text>
                <Text style={s.finSub}>estimée IA</Text>
              </View>
            </View>
          </View>
        </View>

        {/* ── Risk strip */}
        {mainRisk && (
          <View style={s.riskStrip}>
            <Text style={s.riskLabel}>RISQUE PRINCIPAL</Text>
            <Text style={s.riskText}>{mainRisk}</Text>
          </View>
        )}

        {/* ── Recommendation */}
        <View style={s.recoBar}>
          <Text style={s.recoIcon}>★</Text>
          <View style={s.recoContent}>
            <Text style={s.recoTitle}>RECOMMANDATION IA</Text>
            <Text style={s.recoText}>{recommendation}</Text>
          </View>
        </View>

        {/* ── Footer */}
        <View style={s.footer}>
          <Text style={s.footerLeft}>PILOT+ — Confidentiel</Text>
          <Text style={s.footerCenter}>BRIEF COMMERCIAL · 1 PAGE</Text>
          <Text style={s.footerRight}>pilot-plus.fr</Text>
        </View>

      </Page>
    </Document>
  )
}
